apiVersion: v1
appVersion: 0.0.55
description: A Helm chart for Kubernetes
home: https://github.com/jenkins-x-labs/gsm-controller
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/d273e09/images/go.png
name: gsm-controller
version: 0.0.55
